[FEAT] Merge com main (CU #86b39hktk)
PagoPlus/numscript-wasm pull request #1
Opened 2024-12-23 17:06 UTC by Vinocis

2024-12-23 18:57 UTC, fermuch requested changes

2024-12-23 18:57 UTC, fermuch commented on internal/numscript/numscript.go
> +		panic(err)
por que dar panic aqui? Não é melhor ter um erro?

2024-12-23 18:57 UTC, fermuch commented on internal/numscript/numscript.go
> +    }()
isto não deveria ir no inicio?

2024-12-23 18:57 UTC, fermuch commented on internal/numscript/numscript.go
> +	    panic(err)
Mesma coisa aqui. Por que panic ao invés de dar um erro?

2024-12-23 18:58 UTC, fermuch requested changes

2024-12-23 18:58 UTC, fermuch commented on internal/numscript/numscript.go
> +}
Usar `go fmt ./...`

2024-12-23 19:14 UTC, Vinocis commented on internal/numscript/numscript.go
> +		panic(err)
Coloquei panic pra ficar igual o run, mas posso mudar pra um erro

2024-12-23 19:15 UTC, Vinocis commented on internal/numscript/numscript.go
> +	    panic(err)
Esse ja tava como panic, mas posso muda pra um error tbm

2024-12-23 19:49 UTC, fermuch requested changes

2024-12-23 19:49 UTC, fermuch commented on internal/numscript/numscript.go
>  	}
esses dois não íam virar errors agora? (ao invés de panic)

2024-12-23 20:02 UTC, Vinocis commented on internal/numscript/numscript.go
>  	}
Pensei que era só quando desse algum erro na hora de ler o input de algum comando, é pra trocar todos os panics por errors?

2024-12-23 20:14 UTC, fermuch commented on internal/numscript/numscript.go
>  	}
Todos os panics deveriam ser erros, para dar uma ideia ao usuario do que está errado

2024-12-24 16:49 UTC, fermuch requested changes
Falta só aplicar formatting (`go fmt ./...`)

2024-12-26 13:15 UTC, fermuch approved these changes
LGTM!

2024-12-26 13:15 UTC, merged