[FEAT] CI/CD for numscript release #86b37qfxt
PagoPlus/numscript-wasm pull request #2
Opened 2024-12-27 13:00 UTC by debora-be

### **User description**
# WASM Build and Release Pipeline

This PR adds WASM build support via TinyGo and implements an automated release pipeline for the compiled WASM files.

## Changes

### CI/CD Pipeline
- Added TinyGo build step in release workflow
- Configured GitHub Actions to create releases and attach WASM builds
- Set Go version to 1.21 for TinyGo compatibility

### Build Configuration
- Added `.gitignore` entries to exclude WASM builds
- Fixed Go version compatibility issues with TinyGo

### Release Management
- Added release workflow to automatically create GitHub releases
- Configured WASM file upload to releases
- Implemented download script for fetching WASM builds

### Development Environment
- Added Nix development environment configuration
- Added direnv support for automatic environment loading

## Testing
The changes can be tested by:
1. Running the CI pipeline locally with `act`
2. Using the download script: `./scripts/download-wasm.sh`

## Notes
- WASM builds are not included in the repository and must be downloaded from releases

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Added a script to download `numscript.wasm` from GitHub releases, supporting both latest and specific version downloads.
- Updated the CI/CD pipeline to include TinyGo installation and WASM build steps, ensuring compatibility with Go 1.21.5.
- Configured GitHub Actions to automatically upload WASM builds as release artifacts.
- Introduced a Nix flake for setting up the development environment, including necessary dependencies and shell hooks.

___

### **Logs**

Local ran of the release pipeline with success status:

```
[Release/release]   💬  ::debug::Exe path is /opt/hostedtoolcache/goreleaser-action/2.5.1/x64/goreleaser
| GoReleaser latest installed successfully
| [command]/opt/hostedtoolcache/goreleaser-action/2.5.1/x64/goreleaser release --snapshot
|   • skipping announce, publish and validate...
|   • loading environment variables
|   • getting and validating git state
|     • ignoring errors because this is a snapshot     error=git doesn't contain any tags. Either add a tag or use --snapshot
|     • git state                                      commit=dbf61041ff44e14af0c046c0acf6f6e3c885049f branch=feat/ci-cd-for-numscript#86b37qfxt current_tag=v0.0.0 previous_tag=<unknown> dirty=false
|     • pipe skipped                                   reason=disabled during snapshot mode
|   • parsing tag
|   • setting defaults
|   • snapshotting
|     • building snapshot...                           version=0.0.0-SNAPSHOT-dbf6104
|   • running before hooks
|     • running                                        hook=go mod tidy
|   • ensuring distribution directory
|   • setting up metadata
|   • writing release metadata
|   • loading go mod information
|   • build prerequisites
|   • building binaries
|     • building                                       binary=dist/numscript-wasm_wasip1_wasm/numscript.wasm
|     • running hook                                   hook=mkdir -p /home/d/Downloads/numscript-wasm/dist/numscript-wasm_wasip1_wasm
|     • took: 45s
|   • archives
|     • archiving                                      name=dist/numscript-wasm_ 0.0.0-SNAPSHOT-dbf6104_Wasip1_wasm.tar.gz
|   • calculating checksums
|   • writing artifacts metadata
|   • release succeeded after 47s
|   • thanks for using GoReleaser!
[Release/release]   ❓  ::group::Artifacts output
| [{"name":"metadata.json","path":"dist/metadata.json","internal_type":30,"type":"Metadata"},{"name":"numscript.wasm","path":"dist/numscript-wasm_wasip1_wasm/numscript.wasm","goos":"wasip1","goarch":"wasm","target":"wasip1_wasm","internal_type":4,"type":"Binary","extra":{"Binary":"numscript","Builder":"go","Ext":".wasm","ID":"numscript-wasm"}},{"name":"numscript-wasm_ 0.0.0-SNAPSHOT-dbf6104_Wasip1_wasm.tar.gz","path":"dist/numscript-wasm_ 0.0.0-SNAPSHOT-dbf6104_Wasip1_wasm.tar.gz","goos":"wasip1","goarch":"wasm","target":"wasip1_wasm","internal_type":1,"type":"Archive","extra":{"Binaries":["numscript.wasm"],"Checksum":"sha256:3a690bb0f678f12799e3bc0b4edafd43633f3400a5bf4be14707c3a77184a964","Format":"tar.gz","ID":"default","Replaces":null,"WrappedIn":""}},{"name":"numscript-wasm_0.0.0-SNAPSHOT-dbf6104_checksums.txt","path":"dist/numscript-wasm_0.0.0-SNAPSHOT-dbf6104_checksums.txt","internal_type":12,"type":"Checksum","extra":{}}]
[Release/release]   ❓  ::endgroup::
[Release/release]   ❓  ::group::Metadata output
| {"project_name":"numscript-wasm","tag":"v0.0.0","previous_tag":"","version":"0.0.0-SNAPSHOT-dbf6104","commit":"dbf61041ff44e14af0c046c0acf6f6e3c885049f","date":"2025-01-13T01:28:45.783189023Z","runtime":{"goos":"linux","goarch":"amd64"}}
[Release/release]   ❓  ::endgroup::
[Release/release]   ✅  Success - Main Run GoReleaser
[Release/release]   ⚙  ::set-output:: artifacts=[{"name":"metadata.json","path":"dist/metadata.json","internal_type":30,"type":"Metadata"},{"name":"numscript.wasm","path":"dist/numscript-wasm_wasip1_wasm/numscript.wasm","goos":"wasip1","goarch":"wasm","target":"wasip1_wasm","internal_type":4,"type":"Binary","extra":{"Binary":"numscript","Builder":"go","Ext":".wasm","ID":"numscript-wasm"}},{"name":"numscript-wasm_ 0.0.0-SNAPSHOT-dbf6104_Wasip1_wasm.tar.gz","path":"dist/numscript-wasm_ 0.0.0-SNAPSHOT-dbf6104_Wasip1_wasm.tar.gz","goos":"wasip1","goarch":"wasm","target":"wasip1_wasm","internal_type":1,"type":"Archive","extra":{"Binaries":["numscript.wasm"],"Checksum":"sha256:3a690bb0f678f12799e3bc0b4edafd43633f3400a5bf4be14707c3a77184a964","Format":"tar.gz","ID":"default","Replaces":null,"WrappedIn":""}},{"name":"numscript-wasm_0.0.0-SNAPSHOT-dbf6104_checksums.txt","path":"dist/numscript-wasm_0.0.0-SNAPSHOT-dbf6104_checksums.txt","internal_type":12,"type":"Checksum","extra":{}}]
[Release/release]   ⚙  ::set-output:: metadata={"project_name":"numscript-wasm","tag":"v0.0.0","previous_tag":"","version":"0.0.0-SNAPSHOT-dbf6104","commit":"dbf61041ff44e14af0c046c0acf6f6e3c885049f","date":"2025-01-13T01:28:45.783189023Z","runtime":{"goos":"linux","goarch":"amd64"}}
[Release/release] ⭐ Run Post Set up Go
[Release/release]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.5/x64/bin/node /var/run/act/actions/actions-setup-go@v4/dist/cache-save/index.js] user= workdir=
| [command]/opt/hostedtoolcache/go/1.22.10/x64/bin/go env GOMODCACHE
| [command]/opt/hostedtoolcache/go/1.22.10/x64/bin/go env GOCACHE
| /root/go/pkg/mod
| /root/.cache/go-build
[Release/release]   💬  ::debug::Checking zstd --quiet --version
[Release/release]   💬  ::debug::1.4.8
[Release/release]   💬  ::debug::zstd version: 1.4.8
[Release/release]   💬  ::debug::implicitDescendants 'false'
[Release/release]   💬  ::debug::followSymbolicLinks 'true'
[Release/release]   💬  ::debug::implicitDescendants 'false'
[Release/release]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[Release/release]   💬  ::debug::Search path '/root/go/pkg/mod'
[Release/release]   💬  ::debug::Search path '/root/.cache/go-build'
[Release/release]   💬  ::debug::Matched: ../../../../root/go/pkg/mod
[Release/release]   💬  ::debug::Matched: ../../../../root/.cache/go-build
[Release/release]   💬  ::debug::Cache Paths:
[Release/release]   💬  ::debug::["../../../../root/go/pkg/mod","../../../../root/.cache/go-build"]
[Release/release]   💬  ::debug::Archive Path: /tmp/b485d157-d6d9-4da9-bd3a-36029fe3ed0e/cache.tzst
| [command]/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/d/Downloads/numscript-wasm --files-from manifest.txt --use-compress-program zstdmt
[Release/release]   💬  ::debug::File Size: 33938120
[Release/release]   💬  ::debug::Reserving Cache
[Release/release]   💬  ::debug::Resource Url: http://192.168.0.159:42675/_apis/artifactcache/caches
[Release/release]   💬  ::debug::Saving Cache (ID: 15)
[Release/release]   💬  ::debug::Upload cache
[Release/release]   💬  ::debug::Resource Url: http://192.168.0.159:42675/_apis/artifactcache/caches/15
[Release/release]   💬  ::debug::Upload concurre [...]

2024-12-27 14:50 UTC, fermuch requested changes

2024-12-27 14:50 UTC, fermuch commented on .github/workflows/release.yml
> +          tinygo build -o build/numscript.wasm -target wasm ./
deveria ser feito um strip de todo o que seja possível, para deixar o binario o mais pequeno possível

2024-12-27 14:50 UTC, fermuch commented on .github/workflows/release.yml
> +          args: release --rm-dist
o release e obter as deps não deveria ser feito antes de compilar para WASM?

2024-12-27 14:50 UTC, fermuch commented on scripts/download-wasm.sh
> +REPO="formancehq/numscript"
mudar repo

2024-12-27 14:50 UTC, fermuch commented on scripts/download-wasm.sh
> +curl -L "https://github.com/$REPO/releases/download/$VERSION/numscript.wasm" -o priv/wasm/numscript.wasm
verificar se o download não deu erro

2024-12-27 14:50 UTC, fermuch commented on scripts/download-wasm.sh
> +set -e
```suggestion
set -e -o pipefail
```

2024-12-27 14:50 UTC, fermuch commented on flake.nix
como agora vamos ter oficialmente um flake no repo, precisamos adicionar um workflow (do CI) separado para testar se o flake está funcionando bem.

2024-12-27 18:19 UTC, fermuch requested changes

2024-12-27 18:19 UTC, fermuch commented on .github/workflows/nix.yml
> +on: [push, pull_request]
só deveria ser executado quando nos PR para main

2025-01-08 18:40 UTC, fermuch commented
Por favor fazer rebase (ou merge) com main para pegar as novas configurações de goreleaser.

2025-01-20 19:46 UTC, fermuch commented on .github/workflows/release.yml
> +          tinygo build -o build/numscript.wasm -target wasm ./
Não vejo que tinha sido feito o strip. Algumas coisas não são necessárias, como o debug ou o scheduler. Melhor apagar, para o binario ficar mais pequeno.

2025-01-20 19:51 UTC, fermuch requested changes

2025-01-20 19:51 UTC, fermuch commented on .github/workflows/release.yml
> +          fetch-depth: 0
qual seria a utilidade de usar `fetch-depth` aqui?

2025-01-20 19:51 UTC, fermuch commented on .github/workflows/release.yml
> +          sudo dpkg -i tinygo_0.34.0_amd64.deb
melhor descarregar e instalar desde `/tmp`, para não poluir os arquivos do repo

2025-01-20 19:51 UTC, fermuch commented on flake.nix
> +          tree
como seriam usados `nodejs` e `tree` com numscript? e `just`? e `act`?

2025-01-20 19:51 UTC, fermuch commented on internal/parser/antlr/numscript_base_listener.go
> +package antlr // Numscript
não entendi o por que dessa modificação

2025-01-20 19:51 UTC, fermuch commented on internal/parser/antlr/numscript_lexer.go
> +package antlr
tampouco aqui

2025-01-20 19:51 UTC, fermuch commented on internal/parser/antlr/numscript_listener.go
> +package antlr // Numscript
e aqui

2025-01-20 19:51 UTC, fermuch commented on internal/parser/antlr/numscript_parser.go
> +package antlr // Numscript
e também aqui

2025-01-20 19:51 UTC, fermuch commented on internal/parser/parser.go
> +			Cap:   parseValueExpr(sourceCtx.GetLimit()), // Change to GetLimit()
por que foi modificado? e por que o comentario?

2025-01-20 20:11 UTC, Vinocis commented on .github/workflows/release.yml
> +          fetch-depth: 0
Tbm não sei direito pra que serve e não entendi direito na doc, vou perguntar pra debora e retorno.

2025-01-20 20:23 UTC, fermuch commented on .github/workflows/release.yml
> +          fetch-depth: 0
@debora-be

2025-01-20 22:16 UTC, debora-be commented on .github/workflows/release.yml
> +          fetch-depth: 0
@fermuch O `fetch-depth: 0` é necessário porque o GoReleaser precisa do histórico completo do Git para funcionar corretamente. Se definimos como 0, estamos pegando todo o histórico do repositório ao invés de apenas o commit mais recente.

Isso é especialmente importante pois:
- O GoReleaser usa as tags do Git para determinar a próxima versão
- Permite gerar changelogs completos baseados no histórico de commits
- É necessário para calcular corretamente as diferenças entre releases

Se não configurarmos `fetch-depth: 0`, teríamos apenas um tipo de clone que poderia causar problemas durante o processo de release.

2025-01-21 17:00 UTC, Vinocis commented on flake.nix
> +          tree
@debora-be

2025-01-23 16:54 UTC, Vinocis commented on .goreleaser.yaml
> +      - -target=wasi
A flag `target=wasi` no TinyGo faz praticamente a mesma coisa que setar `GOOS=wasip1 GOARCH=wasi`, mas por algum motivo setar as variáveis de ambiente diretamente causa alguns efeitos colaterais, como usar libs que não foram importadas na aplicação (nos testes locais foi `gojs::runtime.ticks`). 

Essa issue e outras que foram marcadas dentro dela falam mais sobre: https://github.com/tinygo-org/tinygo/issues/4682

Como o GoReleaser requer que seja setado um goos (linhas 20 e 21) e um goarch (linhas 22 e 23), infelizmente terão que ser utilizadas junto com a flag `target=wasi`..

P.S.1.: Tanto goos e goarch tem um valor padrão caso não sejam configurados no GoReleaser.

P.S.2.: GoReleaser tem uma config `targets`, mas não é a mesma do TinyGo e nem resolve o problema.

2025-01-23 17:22 UTC, fermuch approved these changes
LGTM!

2025-01-23 17:22 UTC, merged